services:
  - type: web
    name: almacen
    runtime: python
    buildCommand: pip install -r requirements-prod.txt && python build.py
    startCommand: gunicorn app.app:app --workers=1 --timeout=120
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.3
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
